# Generated by Django 5.2.5 on 2025-12-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=30)),
                ('Institute', models.CharField(max_length=100)),
                ('Professors', models.CharField(max_length=50)),
                ('Research_Area', models.CharField(max_length=30)),
                ('URL', models.CharField(max_length=100)),
            ],
        ),
    ]
